version: '3'

services:
  frontend:
    profiles: ["ssl", "no-ssl"]
    image: app/frontend
    container_name: frontend
    environment:
      - API_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    profiles: ["ssl", "no-ssl"]
    image: app/backend
    container_name: backend
    environment:
      - PORT=3000
    depends_on:
      - database

  database:
    profiles: ["ssl", "no-ssl"]
    image: postgres:15
    container_name: backend
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test

  web-ssl:
    profiles: ["ssl"]
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx
      - ./data/ssl/certbot:/etc/letsencrypt
      - ./data/ssl/www:/var/www/certbot
      - ./data/logs/nginx/:/var/log/nginx
    depends_on:
      - backend
      - frontend

  web-no-ssl:
    profiles: ["no-ssl"]
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx-no-ssl:/etc/nginx
      - ./data/ssl/certbot:/etc/letsencrypt
      - ./data/ssl/www:/var/www/certbot
      - ./data/logs/nginx/:/var/log/nginx
    depends_on:
      - backend
      - frontend

  certbot:
    profiles: ["certbot"]
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/ssl/certbot:/etc/letsencrypt
      - ./data/ssl/www:/var/www/certbot
      - ./data/logs/certbot:/var/log/letsencrypt
    command: certonly --webroot -w /var/www/certbot --force-renewal --email {email} -d {domain} -d {www.domain} --agree-tos
