name: Test & Lint

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  Testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/front
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: CD
        run: cd ./apps/front

      - name: Install
        run: pnpm ci

      - name: Build test
        run: pnpm run build

      - name: Lint
        run: pnpm run lint
